global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'hello-service-metrics'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['hello-service:8080']
