server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: CUSTOMER-SERVICE
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/northwind
        username: root
        password: ${MYSQL_PASSWORD:Welcome#123}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
    level:
        org:
            hibernate: OFF
            springframework: DEBUG
        co:
            vinod: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: 'health,info,beans,startup,httptrace,metrics,env'
    endpoint:
        httptrace:
            enabled: true
        startup:
            enabled: true
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
    instance:
        hostname: ${EUREKA_SERVER_HOST:localhost}
        prefer-ip-address: true
