server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: HELLO-SERVICE

logging:
  level:
    org: DEBUG
    co:
      vinod: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'