server:
    port: ${APP_PORT:9090}

spring:
    application:
        name: PRODUCT-SERVICE
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/northwind
        username: root
        password: ${MYSQL_PASSWORD:Welcome#123}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
    level:
        org:
            hibernate: INFO
            springframework: INFO
        co:
            vinod: DEBUG

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
    instance:
        hostname: ${EUREKA_SERVER_HOST:localhost}
        prefer-ip-address: true
